# Generated by Django 2.2.21 on 2021-09-24 11:56

from django.db import migrations, models
import djgeojson.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SamplingStation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('description', models.TextField()),
                ('station_type', models.CharField(max_length=100)),
                ('geom', djgeojson.fields.PointField()),
            ],
        ),
    ]
