# Generated by Django 2.2.21 on 2021-09-25 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mushrooms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mushroomspot',
            name='picture',
            field=models.ImageField(upload_to=''),
        ),
    ]
